#include <stdio.h>
#include <string.h>

#include "pgopps.h"

#define BAR_WIDTH 30

#define COL_RESET   "\033[0m"
#define COL_BOLD    "\033[1m"
#define COL_RED     "\033[31m"
#define COL_YELLOW  "\033[33m"
#define COL_GREEN   "\033[32m"
#define COL_DIM     "\033[2m"

int score_calculate(Finding **findings, int count)
{
    int penalty = 0;
    for (int i = 0; i < count; i++) {
        Finding *f = findings[i];
        while (f) {
            switch (f->priority) {
            case PRIORITY_CRITICAL: penalty += 15; break;
            case PRIORITY_HIGH:     penalty +=  8; break;
            case PRIORITY_MEDIUM:   penalty +=  4; break;
            case PRIORITY_LOW:      penalty +=  1; break;
            default: break;
            }
            f = f->next;
        }
    }
    return (penalty >= 100) ? 0 : 100 - penalty;
}

static const char *score_color(int score)
{
    if (score >= 75) return COL_GREEN;
    if (score >= 50) return COL_YELLOW;
    return COL_RED;
}

static const char *score_grade(int score)
{
    if (score >= 90) return "Excellent";
    if (score >= 75) return "Good";
    if (score >= 50) return "Fair";
    if (score >= 25) return "Poor";
    return "Critical";
}

static const char *score_hint(int score)
{
    if (score >= 90) return "No significant issues found. Keep it up.";
    if (score >= 75) return "Minor improvements available.";
    if (score >= 50) return "Several issues need attention.";
    if (score >= 25) return "Fix HIGH and CRITICAL findings first.";
    return "Significant risks — address CRITICAL findings immediately.";
}

/*
 * Build a UTF-8 progress bar of BAR_WIDTH characters.
 * buf must be at least BAR_WIDTH * 3 + 1 bytes (each block is 3 UTF-8 bytes).
 */
static void build_bar(int score, char *buf, size_t size)
{
    /* █ U+2588 = 0xE2 0x96 0x88  (full block)  */
    /* ░ U+2591 = 0xE2 0x96 0x91  (light shade) */
    static const unsigned char full[]  = { 0xE2, 0x96, 0x88, 0 };
    static const unsigned char empty[] = { 0xE2, 0x96, 0x91, 0 };

    int filled = (score * BAR_WIDTH) / 100;
    char *p = buf;
    size_t rem = size;

    for (int i = 0; i < BAR_WIDTH && rem > 4; i++) {
        const unsigned char *ch = (i < filled) ? full : empty;
        *p++ = (char)ch[0];
        *p++ = (char)ch[1];
        *p++ = (char)ch[2];
        rem -= 3;
    }
    *p = '\0';
}

void score_print(int score, int total_findings, const Options *opts)
{
    if (opts->format == OUTPUT_JSON) return;

    if (opts->format == OUTPUT_MARKDOWN) {
        printf("---\n\n## Opps Score\n\n");
        printf("**%d / 100** — %s\n\n", score, score_grade(score));
        printf("%s (%d finding%s across all checks)\n\n",
               score_hint(score),
               total_findings, total_findings == 1 ? "" : "s");
        printf("---\n\n*Generated by [pgopps](https://github.com/deepcraftdata/pgopps) v%s*\n",
               PGOPPS_VERSION);
        return;
    }

    const char *color = score_color(score);
    const char *grade = score_grade(score);
    const char *hint  = score_hint(score);

    char bar[BAR_WIDTH * 3 + 1];
    build_bar(score, bar, sizeof(bar));

    printf("\n");
    printf("  ─────────────────────────────────────────────\n");
    printf("  %sOpps Score%s  "
           COL_DIM "(%d finding%s across all checks)" COL_RESET "\n\n",
           COL_BOLD, COL_RESET,
           total_findings, total_findings == 1 ? "" : "s");

    printf("  %s%s%s  %s%s%d / 100%s\n\n",
           color, bar, COL_RESET,
           COL_BOLD, color, score, COL_RESET);

    printf("  %s%s%-10s%s  %s%s%s\n",
           COL_BOLD, color, grade, COL_RESET,
           COL_DIM, hint, COL_RESET);

    printf("  ─────────────────────────────────────────────\n\n");
}
